appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: FGioCfOpeE8rY+FwfOcQINbiaNKJsYb1K5IXgkDxeaTs4pVnz6wNduMiKJV1soWC68mQ04tC9OEY+eGeg7/Mygh0Kl3mqcjrBYDUKSAr3R9wOtpNGXk/FwcoE2Kk/+i15o6kKah4JwTVbIG8uN60ZpNwlhJ9bBTcleeLwQ/+s08kqWvYwGmr1Ab8lLUsihhJbvWEwEkB2yiy3BPUqXCjwoCfzIrRZGrTVJiq8jLo3VCGvLETAaLHkotc1FB+4dPLMKgugW364lOZMOa4r4K/o0WdteJ7u9su3ft3/DFrt6eQpM09CTOMmRmAjSVSLuFd+Hf4dVY3MTxOnaaevGh3zbCgdXVXY+aXfmnuT+xC9pEM52k4zmsoA1VXJtqaQHbNLVkdL3aHiGrv69VINx/l5NBqq/tYBrQEJG2hU8uS1dL27bGiQVnEqOoJWNJAg4PDI53iuH9uOa24zvNyUbFiD9jaxSaNz9si8dCPCqPKHfqkdS/uY2CUzGmGjspho3CCekFgYDVfx9S+YKRD9erXJHG8n+VSUKhZhpYVjszx4Bm96bkBEzSfQuZEsAuL16/nrR5H6DLQ4nkp3GGvbVos49aJmFucdVdcu5D79d0TxYFcCBQE/VvqIxUc08cGMctjvAIgM3CYNDyxuGsvBVATuoN4Su6+ZepsGvj0O1Z2N84=
